[tool.poetry]
name = "aoc2020"
version = "0.1.0"
description = "Advent of Code 2020 in Python"
authors = ["Joe Watson <joe_watson@mail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
mypy = "^0.790"
flake8-docstrings = "^1.5.0"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.3.0"
flake8-use-fstring = "^1.1"
flake8-import-order = "^0.18.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
