[tool.poetry]
name = "aoc2020"
version = "0.1.0"
description = "Advent of Code 2020 in Python"
authors = ["Joe Watson <joe_watson@mail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
mypy = "^0.790"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
